### ISSUE TITLE
运行test_IVF.py 出现的若干问题

### ISSUE THREAD

**Issue by Cat2eacher** [Zhaozixiang1228/MMIF-CDDFuse#58]
================================================================================
The test result of TNO 

在运行test_IVF.py  时只到了这一步，确定是cuda，显卡是4070TiS
不知道为啥会卡住不动，写一个问题在这里，有人看到了帮忙解决的话踢我一下

**Comment by Cat2eacher** [comment]
记录1：
一直没报错，注释掉了代码开头的
```python
# import warnings
# import logging
# warnings.filterwarnings("ignore")
# logging.basicConfig(level=logging.CRITICAL)
``` 

现在报错信息是
```bash
_NVIDIA GeForce RTX 4070 Ti SUPER with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4070 Ti SUPER GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))_
``` 


PyTorch 当前安装的版本不支持你的 NVIDIA GeForce RTX 4070 Ti SUPER GPU 的 CUDA Compute Capability (sm_89)
所以我先换个新一点的版本试试

**Comment by Cat2eacher** [comment]
记录2：
记录1里的问题通过更换Pytorch版本已经解决，出现第二个问题
```bash
File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\timm\data\auto_augment.py", line 23, in <module>
from PIL import Image, ImageOps, ImageEnhance, ImageChops
File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\PIL\Image.py", line 100, in <module>
from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。
``` 

解决办法是 Pillow版本降成了9.0.1

**Comment by Cat2eacher** [comment]
记录3：
新的报错问题：
Traceback (most recent call last):
  File "E:\RT\ImageFusion\MMIF-CDDFuse\test_IVF.py", line 54, in <module>
    img_save(fi, img_name.split(sep='.')[0], test_out_folder)
  File "E:\RT\ImageFusion\MMIF-CDDFuse\utils\img_read_save.py", line 21, in img_save
    imsave(os.path.join(savepath, "{}.png".format(imagename)),image)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\skimage\io\_io.py", line 143, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\imageio\v2.py", line 397, in imwrite
    return file.write(im, **kwargs)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\imageio\core\v3_plugin_api.py", line 367, in __exit__
    self.close()
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\imageio\plugins\pillow.py", line 144, in close
    self._flush_writer()
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\imageio\plugins\pillow.py", line 485, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\PIL\Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "D:\Python\Miniconda\envs\cddfuse\lib\site-packages\PIL\PngImagePlugin.py", line 1231, in _save
    raise OSError(f"cannot write mode {mode} as PNG") from e
**OSError: cannot write mode F as PNG**

**Comment by Cat2eacher** [comment]
记录4：
记录3中的问题在另一个issue中找到答案啦！
https://github.com/Zhaozixiang1228/MMIF-CDDFuse/issues/50
